export * from './moviesResInterface'
export * from './movieInterface'
export * from './genresInterface'
export * from './genresResInterface'
export * from './moviesSearchInterface'
export  * from './movieCastInterface'